### PR TITLE
#1291 Fix "Manage" menu bar item

### LINKED ISSUE #1291: Full horizontal list doesn't render upon log in.
List is failing to render fully for Admin - unsure yet if this is affecting other users such as internal or external client users.

Toolbar won't show all options on log in. After refreshing, all options are rendered. It seems that the missing item can vary. Possibly a back-end issue.

On initial log in:

incompleteAdminList

After refreshing:

refreshedAdminList

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #1291 

It was getting the correct `isManage` pref when already logged in, but when logging in, it would run the `else` part of the `onLogin` method (in UserState), which was setting `isManager` to `false`. I think I assumed it would get updated by a subsequent `fetchUserInfo` call, but it doesn't.

So this just fixes that.

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -51,6 +51,7 @@ const config = {
   localStorageJWTKey: 'persistJWT',
   applicantDeadlineCode: 'applicantDeadline',
   isProductionBuild,
+  defaultSystemManagerPermissionName: 'systemManager',
```
Comment (CarlosNZ) [inline src/config.ts:54]: Putting this in here so don't have to hard-code it in two separate places.

File: src/contexts/UserState.tsx [hunk 2]
```diff
@@ -135,7 +140,7 @@ export function UserProvider({ children }: UserProviderProps) {
         newPermissionNames: permissionNames || [],
         newOrgList: orgList || [],
         newIsAdmin: !!isAdmin,
-        newIsManager: false,
+        newIsManager: permissionNames.includes(managementPrefName),
```
Comment (CarlosNZ) [inline src/contexts/UserState.tsx:143]: This is the actual fix

**Review by nmadruga — APPROVED** [review]
Looks good - will be nice to have on the release
