### PR TITLE
#1504 #1505 #1506 Preserve list filters + quick fixes

### LINKED ISSUE #1504: UI quirk -- wrapping in labels
Image

It's only showing up for me locally, not on the live server, so must be some quirk to do with the current column widths. I'd suggested changing the CSS for the labels to not allow any wrapping, and to allow them to overflow their container if needed.

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #1504 #1505 #1506

Most of this is for #1506, the other two are one-liners.

To see #1506 in action, go to the application list, apply some filters, then click on one of the links to applications (either Name, Status or Action cells). Then from the application page, click the "back" link up the top of the page. The list page should be restored with the previous filters unchanged.

Try it for both applicant and reviewer.

Also -- if you can think of any other places that need this filter preservation when going back that I might have missed, please let me know.

See inline comments below for more info

### CODE REVIEW

File: semantic/src/site/globals/site.overrides [hunk 1]
```diff
@@ -1555,6 +1555,10 @@ a:hover {
   margin-bottom: 20px;
 }
 
+.stage-label {
```
Comment (CarlosNZ) [inline semantic/src/site/globals/site.overrides:1558]: This is all that's required to fix #1504. Just prevents any wrapping within the label.

File: src/components/Application/ApplicationContainer.tsx [hunk 2]
```diff
@@ -10,12 +10,17 @@ export interface ApplicationContainerProps {
 
 const ApplicationContainer: React.FC<ApplicationContainerProps> = ({ template, children }) => {
   const { t } = useLanguageProvider()
-  const { replace } = useRouter()
+  const { push, location } = useRouter()
   const {
     userState: { currentUser, isNonRegistered },
   } = useUserState()
+  const [prevQueryString] = useState(location?.state?.prevQuery)
```
Comment (CarlosNZ) [inline src/components/Application/ApplicationContainer.tsx:19]: This shouldn't really need to be a `useState` variable, but the re-renders mess it up. You'll see that the same thing is already done for the Dataview table (going back from the DataView detail page), and we didn't need any extra `useState` there.

One day we can go and hunt down some of these unnecessary re-renders....

File: src/components/List/Cells/ApplicantActionCell.tsx [hunk 3]
```diff
@@ -4,17 +4,22 @@ import { ApplicationStatus } from '../../../utils/generated/graphql'
...
   if (status === ApplicationStatus.ChangesRequired) action = t('ACTION_UPDATE')
   if (status === ApplicationStatus.Draft) action = t('ACTION_CONTINUE')
 
   if (!action)
     return (
-      <Link className="user-action" to={`/application/${serial}`}>
+      <Link
+        className="user-action"
+        to={{ pathname: `/application/${serial}`, state: { prevQuery: location.search } }}
+      >
```
Comment (CarlosNZ) [inline src/components/List/Cells/ApplicantActionCell.tsx:22]: So the basic idea is that we can pass additional state through a link using this syntax. In this case we're passing the filter string so we can use it to generate the "Back" link in the linked component. :)

File: src/utils/hooks/useTimeline/eventInterpretation.ts [hunk 4]
```diff
@@ -228,7 +228,7 @@ const getReviewEvent = (
           ? t('TIMELINE_REVIEW_STARTED', `**${reviewer?.name}**`)
           : t('TIMELINE_CONSOLIDATION_STARTED', `**${reviewer?.name}**`),
       }
-    case value === 'DRAFT' && (prevStatus === 'CHANGES_REQUESTED' || prevStatus === 'PENDING'):
+    case value === 'DRAFT' && ['CHANGES_REQUESTED', 'PENDING', 'DISCONTINUED'].includes(prevStatus):
```
Comment (CarlosNZ) [inline src/utils/hooks/useTimeline/eventInterpretation.ts:231]: Fix for #1505

**Review by fergie-nz — APPROVED** [review]
Nice looks good.
