### PR TITLE
#1303 - Part 2 - Fix assignment available for applications Reviewed or Assigned by others

### LINKED ISSUE #1195: Bug: Reviewer can self-assign after applicant has re-submitted to LOQ
To reproduce this problem:
- Application is put into 'request clarification (List of Questions)' state by User 1
- Appears to User 2 as self-assignable and can self-assign it

See Adam for more details (posted on Subforma on 10th May 2022)

### LINKED ISSUE #1303: Bugs: Reviewer's action, ability to assign and viewing applications not yet submitted
1. One application is currently awaiting amendment by the applicant - is there a status that should be showing here to indicate that to an internal user?

2. Reviewer can see application that has not been submitted 😨 

4. One application has already been reviewed by ‘Jess’ and now user Nicole is prompted to assign the application to themselves - even though the application is awaiting amendment by the applicant.

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes #1303 & fixes #1195

Not sure why this was missing it. But it does fix the problems 2 and 3 described in the bug.... Problem 1 is still wip, it will require a little more work than I was imagined.

Fix for 2 problems listed related to trigger not being called when self-assignment, unassignment or re-assignment happened

### CODE REVIEW

File: src/utils/hooks/useUpdateAssignment.tsx [hunk 1]
```diff
@@ -86,12 +95,20 @@ const createAssignmentPatch = (
   removedSections.forEach((code) => assignedSectionsCodes.delete(code))
   addedSections.forEach((code) => assignedSectionsCodes.add(code))
 
+  const trigger =
+    assignedSectionsCodes.size === 0
+      ? Trigger.OnReviewUnassign
+      : assignment.isSelfAssignable
+      ? Trigger.OnReviewSelfAssign
+      : Trigger.OnReviewAssign
```
Comment (CarlosNZ) [inline src/utils/hooks/useUpdateAssignment.tsx:103]: In our configs, are we actually distinguishing between "OnReviewSelfAssign" and "OnReviewAssign"?

Seems like there'd be quite a bit of duplication between them?

What is the use case when a Self-Assign trigger would cause different actions to an "Assign" trigger?

**Review by CarlosNZ — APPROVED** [review]
Cool, LGTM!

But check my comment about multiple triggers -- just wondering if we actually need both?

File: src/utils/hooks/useUpdateAssignment.tsx (hunk 1 above)
Comment (nmadruga) [reply src/utils/hooks/useUpdateAssignment.tsx:103]: Hmmm I had a look on that, and you are totally right! I think we can get rid of that event! I'll have to do some changes to the back end - and also to remove the old Trigger `Trigger.OnReviewSelfAssign` from core_templates but I'll do it in the Part 1 Back-end (so I don't need to add a new one)

Comment (CarlosNZ) [reply src/utils/hooks/useUpdateAssignment.tsx]: In that case, can we get rid of the "OnReviewSelfAssign" trigger altogether (i.e. remove it from possible Trigger enum values)?

Comment (nmadruga) [reply src/utils/hooks/useUpdateAssignment.tsx]: I tried, but it would mean it fails on snapshots that are still using it. Should it be safe to do?
